version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    restart: always
  backend:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    command: ["nodemon", "app.js"]  # Ensure nodemon is used to restart on changes
    restart: always
